spring:
  application:
    name: web-game

#  security:
#    oauth2:
#      client:
#        provider:
#          naver:
#          kakao:
#        registration:
#          naver:
#          kakao:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/${database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: create # or validate, create-drop, none as needed

    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${your email}
    password: ${your app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${jwt.secret}